version: "3"
services: 
 db:
  restart: always
  container_name: mysql
  command: 
    --default-authentication-plugin=mysql_native_password
    --innodb_use_native_aio=0
  image: mysql:8.0
  environment:
   TZ: Asia/Shanghai
   MYSQL_ROOT_PASSWORD: fanjielei
  ports:
    - 3306:3306
  volumes: 
    - C:\Users\FANJEL\mysql:/var/lib/mysql
    - C:\Users\FANJEL\dockerfiles\configs\mysql\conf.d:/etc/mysql/conf.d
